"""create api client table

Revision ID: 0df00bad2975
Revises: bc2b41a14ca8
Create Date: 2025-10-09 21:11:53.604104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0df00bad2975'
down_revision: Union[str, Sequence[str], None] = 'bc2b41a14ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_ApiClient',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('hashed_api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_ApiClient_api_key'), 'tbl_ApiClient', ['api_key'], unique=True)
    op.create_index(op.f('ix_tbl_ApiClient_client_name'), 'tbl_ApiClient', ['client_name'], unique=True)
    op.create_index(op.f('ix_tbl_ApiClient_hashed_api_key'), 'tbl_ApiClient', ['hashed_api_key'], unique=True)
    op.alter_column('tbl_Patient', 'sex',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'UNKNOWN', name='genderenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_Patient', 'sex',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'UNKNOWN', name='genderenum'),
               nullable=True)
    op.drop_index(op.f('ix_tbl_ApiClient_hashed_api_key'), table_name='tbl_ApiClient')
    op.drop_index(op.f('ix_tbl_ApiClient_client_name'), table_name='tbl_ApiClient')
    op.drop_index(op.f('ix_tbl_ApiClient_api_key'), table_name='tbl_ApiClient')
    op.drop_table('tbl_ApiClient')
    # ### end Alembic commands ###
