"""create relation with user and user role

Revision ID: 189d13b4f5c2
Revises: c02f45138342
Create Date: 2025-10-06 11:47:05.944624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '189d13b4f5c2'
down_revision: Union[str, Sequence[str], None] = 'c02f45138342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_User', 'tbl_UserRole', ['role_id'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_User', type_='foreignkey')
    # ### end Alembic commands ###
