"""add bot-message

Revision ID: 1eac10def8e6
Revises: e9dfe01369f0
Create Date: 2025-11-29 04:10:53.063093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1eac10def8e6'
down_revision: Union[str, Sequence[str], None] = 'e9dfe01369f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_BotMessage',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('message_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('message_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_BotMessage_message_key'), 'tbl_BotMessage', ['message_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_BotMessage_message_key'), table_name='tbl_BotMessage')
    op.drop_table('tbl_BotMessage')
    # ### end Alembic commands ###
