"""Create initial baseline from existing database

Revision ID: 344820af2dfb
Revises: 
Create Date: 2025-10-06 16:39:32.874537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '344820af2dfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_Message', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_message_user_telegram'), 'tbl_Message', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_Message', 'tbl_Patient', ['patient_id'], ['patient_id'])
    op.drop_column('tbl_Message', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_Message', sa.Column('telegram_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tbl_Message', type_='foreignkey')
    op.create_foreign_key(op.f('fk_message_user_telegram'), 'tbl_Message', 'tbl_User', ['telegram_id'], ['telegram_id'])
    op.drop_column('tbl_Message', 'patient_id')
    # ### end Alembic commands ###
