"""add sent and deliverd and paid to enum in tbl_order

Revision ID: 3a8eef5688c6
Revises: 72fc3e982a65
Create Date: 2025-10-26 12:45:00.276011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a8eef5688c6'
down_revision: Union[str, Sequence[str], None] = '72fc3e982a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
