"""add order_status to tbl_order

Revision ID: 72fc3e982a65
Revises: f452f0e5c0c7
Create Date: 2025-10-26 12:15:13.033511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72fc3e982a65'
down_revision: Union[str, Sequence[str], None] = 'f452f0e5c0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

order_status_enum = sa.Enum('CREATED', 'CONFIRM', 'REJECTED', name='orderstatusenum')


def upgrade() -> None:
    """Upgrade schema."""
    order_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_Order', sa.Column('order_status', order_status_enum , nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_Order', 'order_status')
    order_status_enum.drop(op.get_bind())

    # ### end Alembic commands ###
