"""add photo path to patient

Revision ID: bad20e5a7f26
Revises: bdd893179d0c
Create Date: 2025-10-17 03:35:24.405327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bad20e5a7f26'
down_revision: Union[str, Sequence[str], None] = 'bdd893179d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_Patient', sa.Column('photo_paths', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_Patient', 'photo_paths')
    # ### end Alembic commands ###
