"""add_disease_description_and_photos_to_patient

Revision ID: bdd893179d0c
Revises: 0df00bad2975
Create Date: 2025-10-17 01:56:57.955830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bdd893179d0c'
down_revision: Union[str, Sequence[str], None] = '0df00bad2975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_Patient', sa.Column('consultant_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tbl_Patient', sa.Column('special_conditions', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_Patient', 'special_conditions')
    op.drop_column('tbl_Patient', 'consultant_type')
    # ### end Alembic commands ###
