"""create all models without relations

Revision ID: c02f45138342
Revises: 
Create Date: 2025-10-04 15:44:49.775847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c02f45138342'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_DiseaseType',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('diseases_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('diseases_explain', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('diseases_type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('diseases_type_id')
    )
    op.create_table('tbl_Drug',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('drug_pname', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('drug_lname', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('drug_explain', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('drug_how_to_use', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('drugs_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('drugs_id')
    )
    op.create_table('tbl_DrugMap',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('diseases_type_id', sa.Integer(), nullable=False),
    sa.Column('drugs_id', sa.Integer(), nullable=False),
    sa.Column('drugs_map_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('drugs_map_id')
    )
    op.create_table('tbl_Message',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('messages', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('attachment_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('messages_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('messages_id')
    )
    op.create_table('tbl_OrderList',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('order_list_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('order_list_id')
    )
    op.create_table('tbl_Patient',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('fname', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('lname', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('mobile_number', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('specific_diseases', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_tbl_Patient_telegram_id'), 'tbl_Patient', ['telegram_id'], unique=False)
    op.create_table('tbl_PaymentList',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_refer_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('payment_path_file', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('payment_value', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('payment_status', sa.Integer(), nullable=False),
    sa.Column('payment_status_explain', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('payment_list_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('payment_list_id')
    )
    op.create_table('tbl_User',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('national_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('mobile_number', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('national_code')
    )
    op.create_index(op.f('ix_tbl_User_telegram_id'), 'tbl_User', ['telegram_id'], unique=True)
    op.create_table('tbl_UserRole',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('role_type', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('tbl_UserRolePermission',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('form_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('view', sa.Boolean(), nullable=False),
    sa.Column('insert', sa.Boolean(), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_table('tbl_Order',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['tbl_Patient.patient_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_Order')
    op.drop_table('tbl_UserRolePermission')
    op.drop_table('tbl_UserRole')
    op.drop_index(op.f('ix_tbl_User_telegram_id'), table_name='tbl_User')
    op.drop_table('tbl_User')
    op.drop_table('tbl_PaymentList')
    op.drop_index(op.f('ix_tbl_Patient_telegram_id'), table_name='tbl_Patient')
    op.drop_table('tbl_Patient')
    op.drop_table('tbl_OrderList')
    op.drop_table('tbl_Message')
    op.drop_table('tbl_DrugMap')
    op.drop_table('tbl_Drug')
    op.drop_table('tbl_DiseaseType')
    # ### end Alembic commands ###
