"""chenge attachment file in message to get list of attachments 

Revision ID: c3f9e0e49187
Revises: bad20e5a7f26
Create Date: 2025-10-21 23:54:59.597813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql # ممکن است به این ایمپورت نیاز داشته باشید


# revision identifiers, used by Alembic.
revision: str = 'c3f9e0e49187'
down_revision: Union[str, Sequence[str], None] = 'bad20e5a7f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_Message', 'attachment_path',
               existing_type=sa.VARCHAR(length=1000),
               type_=postgresql.JSONB(astext_type=sa.Text()), # توصیه می‌شود از JSONB استفاده کنید
               existing_nullable=True,
               postgresql_using='attachment_path::jsonb' # <<< این خط کلیدی است
               )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_Message', 'attachment_path',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True,
               # استخراج اولین عنصر از آرایه JSON به عنوان متن
               postgresql_using="attachment_path->>0"
               )
