"""Change patient sex field to enum

Revision ID: ce9dd98e770e
Revises: 344820af2dfb
Create Date: 2025-10-07 12:00:24.420661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce9dd98e770e'
down_revision: Union[str, Sequence[str], None] = '344820af2dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

gender_enum = sa.Enum('male', 'female', name='gender_enum')


def upgrade() -> None:
    """Upgrade schema."""
    gender_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_Patient', 'sex',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('MALE', 'FEMALE', name='gender_enum'),
               existing_nullable=True,postgresql_using='sex::gender_enum'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_Patient', 'sex',
               existing_type=sa.Enum('MALE', 'FEMALE', name='gender_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
    gender_enum.drop(op.get_bind(), checkfirst=True)

